export const FOCUSED_CITIES = [
  "Milwaukee WI",
  "Dublin Ireland",
  "Chicago IL",
  "Atlanta GA",
  "St.Paul MN",
  "San Jose CA",
  "Davis CA",
  "Miami FL",
  "San Diego CA",
  "Loma Linda CA",
];

export const OTHER_CITIES = [
  "New York NY",
  "Los Angeles CA",
  "London UK",
  "Tokyo Japan",
  "Paris France",
  "Sydney Australia",
  "Dubai",
  "Singapore",
  "Mumbai India",
  "Toronto Canada",
  "Berlin Germany",
  "Rome Italy",
  "Jilin China",
  "Shenyang China",
  "Changchun China",
  "Beijing China",
  "Shanghai China",
  "Guangzhou China",
  "Chongqing China",
  "Kunming China",
  "Hainan China",
  "Taipei Taiwan",

  // USA
  "Minneapolis MN",
  "Sarasota FL",
  "Orlando FL",
  "Las Vegas NV",
  "Tucson AZ",
  "Houston TX",
  "Dallas TX",
  "Charlotte NC",
  "Washington DC",
  "Seattle WA",

  // International
  "Vancouver Canada",
  "San Jose Costa Rica",
  "Wellington New Zealand",
  "Bahamas",
  "Cayman Islands",
];

export const ALL_CITIES = [...FOCUSED_CITIES, ...OTHER_CITIES];

export const cityChinese: Record<string, string> = {
  "Milwaukee": "密尔沃基",
  "Dublin": "都柏林",
  "Chicago": "芝加哥",
  "Atlanta": "亚特兰大",
  "St. Paul": "圣保罗",
  "St Paul": "圣保罗",
  "Saint Paul": "圣保罗",
  "St.Paul": "圣保罗",
  "Miami": "迈阿密",
  "San Diego": "圣地亚哥",
  "Loma Linda": "洛马林达",
  "San Jose": "圣何塞",
  "Davis": "戴维斯",
  "New York": "纽约",
  "Los Angeles": "洛杉矶",
  "London": "伦敦",
  "Tokyo": "东京",
  "Paris": "巴黎",
  "Sydney": "悉尼",
  "Dubai": "迪拜",
  "Singapore": "新加坡",
  "Mumbai": "孟买",
  "Toronto": "多伦多",
  "Berlin": "柏林",
  "Rome": "罗马",
  "Jilin": "吉林",
  "Shenyang": "沈阳",
  "Changchun": "长春",
  "Beijing": "北京",
  "Shanghai": "上海",
  "Guangzhou": "广州",
  "Chongqing": "重庆",
  "Kunming": "昆明",
  "Hainan": "海南",
  "Taipei": "台北",

  // Additions (countries removed)
  "Minneapolis": "明尼阿波利斯",
  "Sarasota": "萨拉索塔",
  "Orlando": "奥兰多",
  "Las Vegas": "拉斯维加斯",
  "Tucson": "图森",
  "Houston": "休斯顿",
  "Dallas": "达拉斯",
  "Charlotte": "夏洛特",
  "Washington": "华盛顿哥伦比亚特区",
  "Seattle": "西雅图",
  "Vancouver": "温哥华",
  "Wellington": "惠灵顿",
  "Nassau": "拿骚",
  "George Town": "乔治敦",

};

export const getCityChinese = (englishName: string): string => {
  return cityChinese[englishName] || "";
};
